version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_api_platform
    ports:
      - 27017:27017
    volumes:
      - ./data/data-mongo-cypress:/data/db

  # redis:
  #   image: redis:alpine

  server:
    container_name: igbo_api_backend
    restart: always
    image: ijemmao/igbo_api_server
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  # director:
  #   image: agoldis/sorry-cypress-director
  #   container_name: igbo_api_cypress_director
  #   environment:
  #     DASHBOARD_URL: http://localhost:8081
  #     EXECUTION_DRIVER: '../execution/mongo/driver'
  #     MONGODB_URI: 'mongodb://mongodb:27017'
  #     MONGODB_DATABASE: 'sorry-cypress'

  #     SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
  #     MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
  #     MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
  #     MINIO_ENDPOINT: 'storage'
  #     MINIO_URL: 'http://localhost'
  #     MINIO_PORT: '9000'
  #     MINIO_USESSL: 'false'
  #     MINIO_BUCKET: sorry-cypress

  #     REDIS_URI: 'redis://redis:6379'
  #   ports:
  #     - 1234:1234
  #   depends_on:
  #     - mongodb
  #     - storage
  #     - redis

  # api:
  #   image: agoldis/sorry-cypress-api:latest
  #   environment:
  #     MONGODB_URI: 'mongodb://mongodb:27017'
  #     MONGODB_DATABASE: 'sorry-cypress'
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - mongodb

  # dashboard:
  #   image: agoldis/sorry-cypress-dashboard:latest
  #   environment:
  #     GRAPHQL_SCHEMA_URL: http://localhost:4000
  #     GRAPHQL_CLIENT_CREDENTIALS: ''
  #     PORT: 8081
  #     CI_URL: ''
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongodb
  #     - api

  # storage:
  #   image: minio/minio
  #   hostname: 'storage'
  #   environment:
  #     MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
  #     MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
  #   volumes:
  #     - ./data/data-minio-cypress:/data
  #   command: server /data
  #   ports:
  #     - 9000:9000

  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - storage
  #   entrypoint: >
  #     /bin/sh -c "
  #     sleep 3;
  #     /usr/bin/mc config host add myminio http://storage:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
  #     /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
  #     /usr/bin/mc mb myminio/sorry-cypress;
  #     /usr/bin/mc policy set download myminio/sorry-cypress;
  #     /usr/bin/mc policy set public myminio/sorry-cypress;
  #     exit 0;
  #     "
